config/routes.rb
Rails.application.routes.draw do
  resources :departamentos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :produtos, only: [:new, :create, :destroy]
  get "/produtos/busca" => "produtos#busca", as: :busca_produto
  root "produtos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/departamento.rb
class Departamento < ApplicationRecord
end

app/models/produto.rb
class Produto < ApplicationRecord
  belongs_to :departamento
  validates :quantidade, presence: true
  validates :nome, length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departamentos_controller.rb
class DepartamentosController < ApplicationController
  before_action :set_departamento, only: [:show, :edit, :update, :destroy]

  # GET /departamentos
  def index
    @departamentos = Departamento.all
  end

  # GET /departamentos/1
  def show
  end

  # GET /departamentos/new
  def new
    @departamento = Departamento.new
  end

  # GET /departamentos/1/edit
  def edit
  end

  # POST /departamentos
  def create
    @departamento = Departamento.new(departamento_params)

    if @departamento.save
      redirect_to @departamento, notice: 'Departamento was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /departamentos/1
  def update
    if @departamento.update(departamento_params)
      redirect_to @departamento, notice: 'Departamento was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /departamentos/1
  def destroy
    @departamento.destroy
    redirect_to departamentos_url, notice: 'Departamento was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_departamento
      @departamento = Departamento.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def departamento_params
      params.require(:departamento).permit(:nome)
    end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController

  def index
    @produtos_por_nome = Produto.order :nome
    @produtos_por_quantidade = Produto.order :quantidade
  end

  def new
    @produto = Produto.new
    @departamentos = Departamento.all
  end

  def create
    valores = params.require(:produto).permit :nome, :preco, :descricao, :quantidade
    @produto = Produto.new valores
    if @produto.save
      flash[:notice] = "Produto salvo com sucesso"
      redirect_to root_url
    else
      render :new
    end
  end

  def remove
    id = params[:id]
    Produto.destroy(id)
    redirect_to root_url
  end

  def busca
    @nome_a_buscar = params[:nome]
    @produtos = Produto.where "nome like ?", "%#{@nome_a_buscar}%"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departamentos_helper.rb
module DepartamentosHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/departamentos/_form.html.erb
<%= form_with(model: departamento, local: true) do |form| %>
  <% if departamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(departamento.errors.count, "error") %> prohibited this departamento from being saved:</h2>

      <ul>
      <% departamento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/departamentos/edit.html.erb
<h1>Editing Departamento</h1>

<%= render 'form', departamento: @departamento %>

<%= link_to 'Show', @departamento %> |
<%= link_to 'Back', departamentos_path %>

app/views/departamentos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Departamentos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @departamentos.each do |departamento| %>
      <tr>
        <td><%= departamento.nome %></td>
        <td><%= link_to 'Show', departamento %></td>
        <td><%= link_to 'Edit', edit_departamento_path(departamento) %></td>
        <td><%= link_to 'Destroy', departamento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Departamento', new_departamento_path %>

app/views/departamentos/new.html.erb
<h1>New Departamento</h1>

<%= render 'form', departamento: @departamento %>

<%= link_to 'Back', departamentos_path %>

app/views/departamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @departamento.nome %>
</p>

<%= link_to 'Edit', edit_departamento_path(@departamento) %> |
<%= link_to 'Back', departamentos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lojaderoupas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/produtos/_produto.html.erb
<tr>
    <td><%= produto.nome %></td>
    <td><%= produto.descricao %></td>
    <td><%= produto.preco %></td>
    <td><%= button_to "Remover", produto,
                                method: :delete,
                                class: "btn btn-danger",
                                data: { confirm: "Tem certeza que
                                deseja remover #{produto.nome}?" } %>
    </td>
</tr>

app/views/produtos/busca.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <br>
    <div class="container">
      <table class="table table-bordered text-center">
        <thead>
          <tr>
              <th class="text-center">Nome</th>
              <th class="text-center">Descrição</th>
              <th class="text-center">Preço</th>
              <th class="text-center">Quantidade</th>
          </tr>
        </thead>
        <tbody>
          <%= render @produtos  %>
        </tbody>
      </table>
    </div>
  </body>
</html>

app/views/produtos/index.html.erb
<!DOCTYPE html>
<html lang="pt-br" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <%= nav_bar static: :top, brand: "Cakes", brand_link: root_url do %>
      <%= form_tag busca_produto_path,
                         method: :get,
                          class: "navbar-form" do %>
        <div class="form-group">
          <%= text_field_tag :nome, @nome_a_buscar, class: "form-control" %>
          <%= button_to "Buscar", nil, class: "btn-btn-default" %>
        </div>
      <% end %>
    <%   end %>
    <div class="container text-center">
      <% if flash[:notice] %>
        <div class="alert alert-success" role="alert"><%= flash[:notice] %></div>
      <% end %>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th class="text-center">Nome do produto</th>
            <th class="text-center">Descrição</th>
            <th class="text-center">Preço</th>
            <th class="text-center">Quantidade</th>
          </tr>
        </thead>
        <%= render partial: "produto", collection: @produtos_por_nome %>
        <tbody>
        </tbody>
      </table>

      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Nome do produto</th>
            <th>Descrição</th>
            <th>Preço</th>
            <th>Quantidade</th>
          </tr>
        </thead>
        <br>
        <br>
        <tbody>
          <%= render partial: "produto", collection: @produtos_por_nome %>
        </tbody>
      </table>
      <%= link_to "Criar novo produto", new_produto_path, class: "btn btn-primary" %>
    </div>
  </body>
</html>

app/views/produtos/new.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <title></title>
</head>
<body>
  <%= form_for @produto do |f| %>
  <div class="container">

    <% @produto.errors.full_messages.each do |message| %>
    <br>
    <div class="alert alert-danger" role="alert">
      <%= message %>
    </div >
    <% end %>

    <div class="form-group">
      <%= f.label :nome %> <br>
      <%= f.text_field :nome, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :quantidade %><br>
      <%= f.number_field :quantidade, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :descricao %><br>
      <%= f.text_area :descricao, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :preco %><br>
      <%= f.number_field :preco, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :departamento %>
      <%= f.collection_select :departament_id, @departamentos, :id, :nome %>
    </div>
    <br>
    <%= f.submit "Criar produto", class: "btn btn-primary " %>
  </div>
  <% end %>
</body>
</html>